const name = "Francisco";
const lastName = "Paneque";
const estudiante = name.concat(" ").concat(lastName);
const estudianteMayus = estudiante.toUpperCase();
const estudianteMinus = estudiante.toLowerCase();
const estudianteLength = estudiante.length();
const inicialNombre = name.substring(0, 1)
const finalApellido = lastname.substring(lastName.length - 1, lastName.length);
const borrarEspacios = estudiante.replace(/ /g, "");
const verdadName = estudiante.includes(name);